app.config(['I18NServiceProvider',
    function (i18NServiceProvider) {
        i18NServiceProvider.add({
            EN_US: {
                SOBRE: {
                    TITULO: 'About',
                    P_1: 'After the direct observation of the sun, monitoring the physical parameters of the solar plasma on the Lagrangian Point L1 is the best experimental tool to understand and estimate the possible effects that changes in the space weather condition can cause on natural terrestrial phenomena (such as geomagnetic storms and auroras), on technological systems and on living beings. In order to summarize and standardize the description of the temporal variations of these parameters, we created (initially) four indices to describe the space weather conditions in the interplanetary medium close to the Earth taking into account the solar wind speed and magnetic configuration and its effects on the magnetopause, as is shown in Table 1.',
                    P_2: 'All the indices were defined so that they have values between 0 and 5 where 0 means typical conditions from calm periods and the remaining values indicate some level of disturbance in increasing order of magnitude. More information about the index scale levels are given in the Table 2.',
                    T_1_TITULO: 'Table 1',
                    T_1_DESCRICAO: 'Overview of the 4 indices of the interplanetary medium.',
                    T_1_CABECALHO1: 'Index',
                    T_1_CABECALHO2: 'Monitored parameter(s)',
                    T_1_CABECALHO3: 'Monitored behavior',
                    T_1_CABECALHO4: 'Description',
                    T_1: 'Solar wind speed',
                    T_2: 'Southward component of the interplanetary magnetic field',
                    T_3: 'Magnitude of the interplanetary magnetic field',
                    T_4: 'Dynamic pressure of the solar wind and southward component of the interplanetary magnetic field',
                    T_1_1: 'Solar wind speed increase registered over the last hours',
                    T_1_2: 'Magnitude of the interplanetary magnetic field directed southward of the ecliptic plane',
                    T_1_3: 'Enhancement of the magnitude of the interplanetary magnetic field',
                    T_1_4: 'Compression of the dayside magnetopause',
                    T_1_1_1: 'Increases in the solar wind speed higher than 100 km/s are registered by this index both when the increase is observed suddenly (i.e., during observations of interplanetary shock waves) and when it is observed gradually over tens of hours as is the case of high-speed solar wind streams caused by coronal holes. The level 5 is associated to increases higher than 500 km/s associated to fast interplanetary coronal mass ejections and fast solar wind streams.',
                    T_1_2_2: 'Associated to the arrival of interplanetary structures with magnetic configuration that can generate geomagnetic storms. I.Z is zero when the interplanetary magnetic field is northward or southward oriented with small magnitude. This index increases as much as the southward component increases. Generally, the geomagnetic storms  are observed in the hours following the observation of this index increase.',
                    T_1_3_3: 'This index is associated to the arrival of high-speed solar wind streams, interplanetary shock waves, interplanetary coronal mass ejections and most of the heliospheric current sheet sector crossings. I. B is zero when the magnitude of the interplanetary magnetic field is close to 5 nT. Disturbances with magnitude close to 10 nT are classified as level 1. If the magnitude of the interplanetary magnetic field reaches values higher than 40 nT (a value observed on extreme disturbances associated the interplanetary coronal mass ejections) the level 5 is reached.',
                    T_1_4_4: 'Associated to the interplanetary structures influence on the magnetosphere. I.C is at level 0 during calm periods, when the magnetopause position typically ranges between 10 and 11 Earth’s radii. When the magnetopause is compressed up to 6 Earth’s radii, I.C reaches level 5.',
                    T_2_TITULO: 'Table 2',
                    T_2_DESCRICAO: 'Typical description of and average frequency of observation of each index scale level.',
                    T_2_CABECALHO1: 'Level',
                    T_2_CABECALHO2: 'Disturbance',
                    T_2_CABECALHO3: 'Average observation',
                    T_2_1: 'Extreme',
                    T_2_2: 'Severe',
                    T_2_3: 'Strong',
                    T_2_4: 'Moderate',
                    T_2_5: 'Minor',
                    T_2_6: 'Absent',
                    T_2_1_1: 'one day every two years',
                    T_2_2_2: 'one day every six months',
                    T_2_3_3: 'one day every month',
                    T_2_4_4: 'one day every fortnight',
                    T_2_5_5: 'one day every week',
                    T_2_6_6: 'one day every 1.5 days',
                    TIME_T: 'Scientific and technical development',
                    TIME_T2: 'Supporting scientists',
                    TIME_T3: 'IT Team',
                    TIME_MAIN1: 'Dr. Rafael Rodrigues Souza de Mendonça',
                    TIME_MAIN2: 'Dr. Carlos Roberto Braga',
                    TIME2: 'Dra. Lígia Alves da Silva',
                    TIME3: 'Dr. Clezio Marcos De Nardin',
                    TIME4: 'Dr. Alisson Dal Lago',
                    TIME5: 'Dr. Ezequiel Echer',
                    TIME6: 'Dra. Laysa Cristina Araújo Resende',
                    TIME7: 'Dr. Fábio Becker Guedes',
                    TIME71: 'Carolina de Sousa do Carmo',
                    TIME8: 'Dr. José Roberto Cecatto',
                    TIME9: 'Dra. Lívia Ribeiro Alves',
                    TIME10: 'Dr. Joaquim Eduardo Rezende Costa',
                    TIME11: 'Dr. Odim Mendes Junior',
                    TIME12: 'Dr. Daiki Koga',
                    TIME13: 'MSc. Paulo França Barbosa Neto',
                    TIME14: 'Dr. Marcelo Banik de Pádua',
                    TIME15: 'Carlos Adriano Portes, Project manager, EMBRACE ',
                    TIME16: 'Débora Cristina de Azevedo, Programmer analyst, EMBRACE',
                    TIME17: 'Fauéz Abraão de Oliveira Passos, Linux systems analyst, EMBRACE',
                    TIME18: 'Guilherme da Costa Botossi, System analyst, EMBRACE',
                    TIME19: 'MSc. Rodolfo Georjute Lotte, System analyst, EMBRACE',
                    TIME20: 'Vitor Ezequiel de Paula Santos, System analyst, EMBRACE',
                    VERSAO: 'Version 1.0',
                    AGRADECIMENTOS: 'Acknowledgements',
                    AGRADECIMENTOS_TEXTO: 'The solar wind plasma and magnetic field data are taken from plasma and magnetic field instruments onboard the DSCOVR(SWPC/NOAA). The techniques and methodologies used on this product were supported by the following projects: PCI (454779/2015-1 and 300687/2016-8), FAPESP (2014/24711-6) and CNPq (406331/2015-4).'
                }
            }
        });
    }
]);