app.config(['I18NServiceProvider',
    function (i18NServiceProvider) {
        i18NServiceProvider.add({
            PT_BR: {
                SOBRE: {
                    TITULO: 'Sobre',
                    P_1: 'Após a observação solar direta, o monitoramento dos parâmetros físicos do plasma solar no ponto Lagrangiano L1 é a melhor ferramenta experimental para se entender e estimar os possíveis efeitos que mudanças no clima espacial poderão causar em sistemas tecnológicos, seres vivos e em fenômenos terrestres naturais. A fim de sumarizar e padronizar a descrição das variações temporais desses parâmetros, foram criados (inicialmente) quatro índices que descrevem as condições do clima espacial do meio interplanetário no espaço próximo à Terra com base na velocidade e configuração magnética do vento solar, além de sua atuação sobre a magnetopausa conforme é mostrado na Tabela 1.',
                    P_2: 'Todos os índices descritos nesta tabela foram definidos de forma que tenham níveis entre 0 e 5, onde 0 indica condições típicas de períodos calmos e os demais valores indicam algum tipo de perturbação em nível crescente de intensidade conforme é mostrado na Tabela 2.',
                    T_1_TITULO: 'Tabela 1',
                    T_1_DESCRICAO: 'Descrição geral dos 4 índices do Meio Interplanetário.',
                    T_1_CABECALHO1: 'Índice',
                    T_1_CABECALHO2: 'Parâmetro(s) monitorado(s)',
                    T_1_CABECALHO3: 'Comportamento monitorado',
                    T_1_CABECALHO4: 'Descrição',
                    T_1: 'Velocidade do Vento solar',
                    T_2: 'Componente sul do campo magnético interplanetário',
                    T_3: 'Magnitude do campo magnético interplanetário',
                    T_4: 'Pressão dinâmica do Vento Solar e componente sul do campo magnético interplanetário',
                    T_1_1: 'Aumento na velocidade do Vento Solar acumulado nas últimas horas',
                    T_1_2: 'Magnitude da componente  do campo magnético interplanetário direcionada ao sul do plano da eclíptica',
                    T_1_3: 'Intensificação da magnitude do campo magnético interplanetário',
                    T_1_4: 'Compressão do lado diurno da Magnetopausa',
                    T_1_1_1: 'Aumentos de velocidade superiores a 100 km/s são considerados pelo índice tanto nos casos em que ele é súbito (geralmente causado por ondas de choques interplanetárias) quanto nos casos em que ele é gradual e ocorre em períodos de dezenas de horas, como é o caso de diversos feixes de vento solar rápido causados por buracos coronais. O nível 5 se refere a aumentos superiores a 500 km/s associados a ICMEs rápidas e feixes de vento solar rápidos expressivos.',
                    T_1_2_2: 'Associado a passagem de estruturas com orientação magnética que possibilite a ocorrência de tempestades geomagnéticas. Quando o campo magnético interplanetário está orientado na direção norte ou é pouco expressivo na direção sul, seu nível será zero. A medida que o componente sul se intensifica, seu nível aumenta. Geralmente, nas horas seguintes ao seu incremento, são observadas tempestades geomagnéticas.',
                    T_1_3_3: 'Associado tanto a chegada de feixes de vento solar rápido, cruzamentos da lâmina de corrente heliosférica, choques interplanetários e ejeções coronais de massa interplanetárias. Enquanto valores próximos de 5 nT são considerados nível 0, pequenas intensificações cujo valor máximo seja da ordem de 10 nT são caracterizadas nível 1. Valores extremos (por volta de 40 nT) registrados tipicamente durante eventos extremos são considerados nível 5.',
                    T_1_4_4: 'Está associado influência de estruturas interplanetárias na magnetosfera. Seu nível será próximo de zero em períodos calmos, quando a posição da magnetopausa permanece entre 10 e 11 raios terrestres. Quando a posição da magnetopausa é comprimida para até aproximadamente 6 raios terrestres, atribui-se o nível 5.',
                    T_2_TITULO: 'Tabela 2',
                    T_2_DESCRICAO: 'Descrição típica e frequência média de observação de cada um dos níveis de escala de perturbação.',
                    T_2_CABECALHO1: 'Nível',
                    T_2_CABECALHO2: 'Perturbação',
                    T_2_CABECALHO3: 'Observado em média',
                    T_2_1: 'Extrema',
                    T_2_2: 'Severa',
                    T_2_3: 'Forte',
                    T_2_4: 'Moderada',
                    T_2_5: 'Pequena',
                    T_2_6: 'Ausente',
                    T_2_1_1: 'um dia a cada 2 anos',
                    T_2_2_2: 'um dia a cada 6 meses',
                    T_2_3_3: 'um dia a cada 1 mês',
                    T_2_4_4: 'um dia a cada quinzena',
                    T_2_5_5: 'um dia a cada semana',
                    T_2_6_6: 'um dia a cada 1,5 dias',
                    TIME_T: 'Desenvolvimento Científico e Técnico',
                    TIME_T2: 'Cientistas Colaboradores',
                    TIME_T3: 'Equipe TI',
                    TIME_MAIN1: 'Dr. Rafael Rodrigues Souza de Mendonça',
                    TIME_MAIN2: 'Dr. Carlos Roberto Braga',
                    TIME2: 'Dra. Lígia Alves da Silva',
                    TIME3: 'Dr. Clezio Marcos De Nardin',
                    TIME4: 'Dr. Alisson Dal Lago',
                    TIME5: 'Dr. Ezequiel Echer',
                    TIME6: 'Dra. Laysa Cristina Araújo Resende',
                    TIME7: 'Dr. Fábio Becker Guedes',
                    TIME71: 'Carolina de Sousa do Carmo',
                    TIME8: 'Dr. José Roberto Cecatto',
                    TIME9: 'Dra. Lívia Ribeiro Alves',
                    TIME10: 'Dr. Joaquim Eduardo Rezende Costa',
                    TIME11: 'Dr. Odim Mendes Junior',
                    TIME12: 'Dr. Daiki Koga',
                    TIME13: 'MSc. Paulo França Barbosa Neto',
                    TIME14: 'Dr. Marcelo Banik de Pádua',
                    TIME15: 'Carlos Adriano Portes, Gerente de projetos',
                    TIME16: 'Débora Cristina de Azevedo, Analista Programador',
                    TIME17: 'Fauéz Abraão de Oliveira Passos, Analista de sistemas Linux',
                    TIME18: 'Guilherme da Costa Botossi, Analista de sistemas',
                    TIME19: 'MSc. Rodolfo Georjute Lotte, Analista de sistemas',
                    TIME20: 'Vitor Ezequiel de Paula Santos, Analista de sistemas',
                    VERSAO: 'Versão 1.0',
                    AGRADECIMENTOS: 'Agradecimentos',
                    AGRADECIMENTOS_TEXTO: 'Os dados do meio interplanetário são obtidos através da sonda espacial DSCOVR (SWPC/NOAA). As técnicas e metodologias utilizadas neste produto foram desenvolvidas ao longo dos projetos PCI (Institucional: 454779/2015-1 e Individual: 300687/2016-8), FAPESP (2014/24711-6) e CNPq (406331/2015-4).'
                }
            }
        });
    }
]);